### ISSUE TITLE
How to make static pages accessible?

### ISSUE THREAD

**Issue by schiessle** [idno/StaticPages#3]
I just create a static page and can access it with the url "mydomain.com/pages/page_title". But I can't find any link to the static page on my main page.  I could edit my profile and add it to "Your websites" but I'm not sure if this is the right way to do it. What's the intended way to make a static page accessible for visitors?

**Comment by benwerd** [comment]
Hmm. It should be making a top-bar navigation link for you? If not,
something is going wrong. We're happy to check it out.

On Sat, Mar 14, 2015 at 12:55 PM, Björn Schießle notifications@github.com
wrote:

> I just create a static page and can access it with the url "
> mydomain.com/pages/page_title". But I can't find any link to the static
> page on my main page. I could edit my profile and add it to "Your websites"
> but I'm not sure if this is the right way to do it. What's the intended way
> to make a static page accessible for visitors?
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/idno/StaticPages/issues/3.

## 

Ben Werdmuller
http://goog_1933028737
benwerd.com | werd.io

+1 (312) 488-9373

**Comment by schiessle** [comment]
Would be great if you could have a look, this is my instance: https://stream.schiessle.org
and this is the static page I created: https://stream.schiessle.org/pages/hello-world

I can't find any link to it. Do you need any additional information?

**Comment by schiessle** [comment]
I migrated my installation from git master to your stable releases from the tar file. Now the static page is at the navigation bar. Don't know what was wrong with my git installation.

... so I close this issue
